name: test-and-trigger-a-deployment
on:
  push:
    branches:
      - master
  workflow_dispatch: # Manual github trigger (by pressing "Run workflow" on Github "Actions" tab)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test suite (includes pip install)
        run: make test

  trigger-deployment:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch # Sends webhook to `openfisca-nsw-deploy` repo which triggers deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CR_PAT }}
          repository: energy-savings-scheme/openfisca-nsw-deploy
          event-type: submodule-updated
